### ISSUE TITLE
bug: 제품 가격 세팅 버그

### ISSUE THREAD

**Issue by syrius527** [guheyo/guheyo-server#128]
wtb-server version: v0.1.0-beta

## 현재 동작
디스코드 메세지
<img width="703" alt="image" src="https://github.com/guheyo/guheyo-server/assets/83915027/4e10fb76-3113-4f13-bf0c-25e0d0757236">
wtb 포스트
<img width="1329" alt="image" src="https://github.com/guheyo/guheyo-server/assets/83915027/589ca459-d24b-42ee-8783-390d4a044c83">

디스코드 api로 가져온 메세지를 db insert하는 과정에서 .5표기가 price에 반영되지 않고 content로 넘어가는 것으로 보임

## 예상 동작
.5를 price에 반영하도록 수정되어야 함

혹시 의도된 동작이라면 말씀해주세요!

**Comment by keypport** [comment]
안녕하세요
입력 받는 숫자 가격은 만원 단위로 가정하고 있는데
소수점 첫째자리까지는 살려두는 게 더 좋을 것 같아요

제보 감사합니다.
현재 develop branch를 통해 개편 작업을 하고 있어서, develop에 먼저 반영해 둘게요

**Comment by keypport** [comment]
https://github.com/guheyo/guheyo-server/pull/130
